module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_environment_variable_auth_response =
          {
            networking: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking,
            secret_name: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_
          }

        class BetaManagedAgentsEnvironmentVariableAuthResponse < Anthropic::Internal::Type::BaseModel
          attr_accessor networking: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking

          attr_accessor secret_name: String

          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_

          def initialize: (
            networking: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking,
            secret_name: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_
          ) -> void

          def to_hash: -> {
            networking: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking,
            secret_name: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_
          }

          type networking =
            Anthropic::Beta::Vaults::BetaManagedAgentsUnrestrictedCredentialNetworkingResponse
            | Anthropic::Beta::Vaults::BetaManagedAgentsLimitedCredentialNetworkingResponse

          module Networking
            extend Anthropic::Internal::Type::Union

            def self?.variants: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking]
          end

          type type_ = :environment_variable

          module Type
            extend Anthropic::Internal::Type::Enum

            ENVIRONMENT_VARIABLE: :environment_variable

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_]
          end
        end
      end
    end
  end
end
