module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_limited_credential_networking_response =
          {
            allowed_hosts: ::Array[String],
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsLimitedCredentialNetworkingResponse::type_
          }

        class BetaManagedAgentsLimitedCredentialNetworkingResponse < Anthropic::Internal::Type::BaseModel
          attr_accessor allowed_hosts: ::Array[String]

          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsLimitedCredentialNetworkingResponse::type_

          def initialize: (
            allowed_hosts: ::Array[String],
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsLimitedCredentialNetworkingResponse::type_
          ) -> void

          def to_hash: -> {
            allowed_hosts: ::Array[String],
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsLimitedCredentialNetworkingResponse::type_
          }

          type type_ = :limited

          module Type
            extend Anthropic::Internal::Type::Enum

            LIMITED: :limited

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsLimitedCredentialNetworkingResponse::type_]
          end
        end
      end
    end
  end
end
