module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_credential =
          {
            id: String,
            archived_at: Time?,
            auth: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::auth,
            created_at: Time,
            metadata: ::Hash[Symbol, String],
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::type_,
            updated_at: Time,
            vault_id: String,
            display_name: String?
          }

        class BetaManagedAgentsCredential < Anthropic::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor archived_at: Time?

          attr_accessor auth: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::auth

          attr_accessor created_at: Time

          attr_accessor metadata: ::Hash[Symbol, String]

          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::type_

          attr_accessor updated_at: Time

          attr_accessor vault_id: String

          attr_accessor display_name: String?

          def initialize: (
            id: String,
            archived_at: Time?,
            auth: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::auth,
            created_at: Time,
            metadata: ::Hash[Symbol, String],
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::type_,
            updated_at: Time,
            vault_id: String,
            ?display_name: String?
          ) -> void

          def to_hash: -> {
            id: String,
            archived_at: Time?,
            auth: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::auth,
            created_at: Time,
            metadata: ::Hash[Symbol, String],
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::type_,
            updated_at: Time,
            vault_id: String,
            display_name: String?
          }

          type auth =
            Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthAuthResponse
            | Anthropic::Beta::Vaults::BetaManagedAgentsStaticBearerAuthResponse
            | Anthropic::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse

          module Auth
            extend Anthropic::Internal::Type::Union

            def self?.variants: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::auth]
          end

          type type_ = :vault_credential

          module Type
            extend Anthropic::Internal::Type::Enum

            VAULT_CREDENTIAL: :vault_credential

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredential::type_]
          end
        end
      end
    end
  end
end
