module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_unrestricted_credential_networking_response =
          {
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsUnrestrictedCredentialNetworkingResponse::type_
          }

        class BetaManagedAgentsUnrestrictedCredentialNetworkingResponse < Anthropic::Internal::Type::BaseModel
          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsUnrestrictedCredentialNetworkingResponse::type_

          def initialize: (
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsUnrestrictedCredentialNetworkingResponse::type_
          ) -> void

          def to_hash: -> {
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsUnrestrictedCredentialNetworkingResponse::type_
          }

          type type_ = :unrestricted

          module Type
            extend Anthropic::Internal::Type::Enum

            UNRESTRICTED: :unrestricted

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsUnrestrictedCredentialNetworkingResponse::type_]
          end
        end
      end
    end
  end
end
