module Anthropic
  module Models
    module Beta
      module Vaults
        type credential_update_params =
          {
            vault_id: String,
            credential_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth,
            display_name: String?,
            metadata: ::Hash[Symbol, String?]?,
            betas: ::Array[Anthropic::Models::anthropic_beta]
          }
          & Anthropic::Internal::Type::request_parameters

        class CredentialUpdateParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor vault_id: String

          attr_accessor credential_id: String

          attr_reader auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth?

          def auth=: (
            Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth
          ) -> Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth

          attr_accessor display_name: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

          def betas=: (
            ::Array[Anthropic::Models::anthropic_beta]
          ) -> ::Array[Anthropic::Models::anthropic_beta]

          def initialize: (
            vault_id: String,
            credential_id: String,
            ?auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth,
            ?display_name: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            vault_id: String,
            credential_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth,
            display_name: String?,
            metadata: ::Hash[Symbol, String?]?,
            betas: ::Array[Anthropic::Models::anthropic_beta],
            request_options: Anthropic::RequestOptions
          }

          type auth =
            Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthUpdateParams
            | Anthropic::Beta::Vaults::BetaManagedAgentsStaticBearerUpdateParams
            | Anthropic::Beta::Vaults::BetaManagedAgentsEnvironmentVariableUpdateParams

          module Auth
            extend Anthropic::Internal::Type::Union

            def self?.variants: -> ::Array[Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth]
          end
        end
      end
    end
  end
end
