module Anthropic
  module Models
    module Beta
      module Vaults
        type credential_create_params =
          {
            vault_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth,
            display_name: String?,
            metadata: ::Hash[Symbol, String],
            betas: ::Array[Anthropic::Models::anthropic_beta]
          }
          & Anthropic::Internal::Type::request_parameters

        class CredentialCreateParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor vault_id: String

          attr_accessor auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth

          attr_accessor display_name: String?

          attr_reader metadata: ::Hash[Symbol, String]?

          def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

          def betas=: (
            ::Array[Anthropic::Models::anthropic_beta]
          ) -> ::Array[Anthropic::Models::anthropic_beta]

          def initialize: (
            vault_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth,
            ?display_name: String?,
            ?metadata: ::Hash[Symbol, String],
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            vault_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth,
            display_name: String?,
            metadata: ::Hash[Symbol, String],
            betas: ::Array[Anthropic::Models::anthropic_beta],
            request_options: Anthropic::RequestOptions
          }

          type auth =
            Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthCreateParams
            | Anthropic::Beta::Vaults::BetaManagedAgentsStaticBearerCreateParams
            | Anthropic::Beta::Vaults::BetaManagedAgentsEnvironmentVariableCreateParams

          module Auth
            extend Anthropic::Internal::Type::Union

            def self?.variants: -> ::Array[Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth]
          end
        end
      end
    end
  end
end
