module Anthropic
  module Models
    type content_block_param =
      Anthropic::TextBlockParam
      | Anthropic::ImageBlockParam
      | Anthropic::DocumentBlockParam
      | Anthropic::SearchResultBlockParam
      | Anthropic::ThinkingBlockParam
      | Anthropic::RedactedThinkingBlockParam
      | Anthropic::ToolUseBlockParam
      | Anthropic::ToolResultBlockParam
      | Anthropic::ServerToolUseBlockParam
      | Anthropic::WebSearchToolResultBlockParam
      | Anthropic::WebFetchToolResultBlockParam
      | Anthropic::CodeExecutionToolResultBlockParam
      | Anthropic::BashCodeExecutionToolResultBlockParam
      | Anthropic::TextEditorCodeExecutionToolResultBlockParam
      | Anthropic::ToolSearchToolResultBlockParam
      | Anthropic::ContainerUploadBlockParam
      | Anthropic::MidConversationSystemBlockParam

    module ContentBlockParam
      extend Anthropic::Internal::Type::Union

      def self?.variants: -> ::Array[Anthropic::Models::content_block_param]
    end
  end
end
