module Anthropic
  module Models
    class BetaRefusalStopDetails = Beta::BetaRefusalStopDetails

    module Beta
      type beta_refusal_stop_details =
        {
          category: Anthropic::Models::Beta::BetaRefusalStopDetails::category?,
          explanation: String?,
          fallback_credit_token: String?,
          fallback_has_prefill_claim: bool?,
          recommended_model: String?,
          type: :refusal
        }

      class BetaRefusalStopDetails < Anthropic::Internal::Type::BaseModel
        attr_accessor category: Anthropic::Models::Beta::BetaRefusalStopDetails::category?

        attr_accessor explanation: String?

        attr_accessor fallback_credit_token: String?

        attr_accessor fallback_has_prefill_claim: bool?

        attr_accessor recommended_model: String?

        attr_accessor type: :refusal

        def initialize: (
          category: Anthropic::Models::Beta::BetaRefusalStopDetails::category?,
          explanation: String?,
          fallback_credit_token: String?,
          fallback_has_prefill_claim: bool?,
          recommended_model: String?,
          ?type: :refusal
        ) -> void

        def to_hash: -> {
          category: Anthropic::Models::Beta::BetaRefusalStopDetails::category?,
          explanation: String?,
          fallback_credit_token: String?,
          fallback_has_prefill_claim: bool?,
          recommended_model: String?,
          type: :refusal
        }

        type category = :cyber | :bio | :frontier_llm | :reasoning_extraction

        module Category
          extend Anthropic::Internal::Type::Enum

          CYBER: :cyber
          BIO: :bio
          FRONTIER_LLM: :frontier_llm
          REASONING_EXTRACTION: :reasoning_extraction

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaRefusalStopDetails::category]
        end
      end
    end
  end
end
