module Anthropic
  module Models
    module BetaManagedAgentsDeploymentInitialEventParams = Beta::BetaManagedAgentsDeploymentInitialEventParams

    module Beta
      type beta_managed_agents_deployment_initial_event_params =
        Anthropic::Beta::Sessions::BetaManagedAgentsUserMessageEventParams
        | Anthropic::Beta::Sessions::BetaManagedAgentsUserDefineOutcomeEventParams
        | Anthropic::Beta::Sessions::BetaManagedAgentsSystemMessageEventParams

      module BetaManagedAgentsDeploymentInitialEventParams
        extend Anthropic::Internal::Type::Union

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_managed_agents_deployment_initial_event_params]
      end
    end
  end
end
