module Anthropic
  module Models
    class BetaManagedAgentsDeploymentUserMessageEvent = Beta::BetaManagedAgentsDeploymentUserMessageEvent

    module Beta
      type beta_managed_agents_deployment_user_message_event =
        {
          content: ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::content],
          type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::type_
        }

      class BetaManagedAgentsDeploymentUserMessageEvent < Anthropic::Internal::Type::BaseModel
        attr_accessor content: ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::content]

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::type_

        def initialize: (
          content: ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::content],
          type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::type_
        ) -> void

        def to_hash: -> {
          content: ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::content],
          type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::type_
        }

        type content =
          Anthropic::Beta::Sessions::BetaManagedAgentsTextBlock
          | Anthropic::Beta::Sessions::BetaManagedAgentsImageBlock
          | Anthropic::Beta::Sessions::BetaManagedAgentsDocumentBlock

        module Content
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::content]
        end

        type type_ = :"user.message"

        module Type
          extend Anthropic::Internal::Type::Enum

          USER_MESSAGE: :"user.message"

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserMessageEvent::type_]
        end
      end
    end
  end
end
