module Anthropic
  module Models
    class BetaManagedAgentsScheduleParams = Beta::BetaManagedAgentsScheduleParams

    module Beta
      type beta_managed_agents_schedule_params =
        {
          expression: String,
          timezone: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsScheduleParams::type_
        }

      class BetaManagedAgentsScheduleParams < Anthropic::Internal::Type::BaseModel
        attr_accessor expression: String

        attr_accessor timezone: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsScheduleParams::type_

        def initialize: (
          expression: String,
          timezone: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsScheduleParams::type_
        ) -> void

        def to_hash: -> {
          expression: String,
          timezone: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsScheduleParams::type_
        }

        type type_ = :cron

        module Type
          extend Anthropic::Internal::Type::Enum

          CRON: :cron

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsScheduleParams::type_]
        end
      end
    end
  end
end
