module Anthropic
  module Models
    class BetaManagedAgentsEffortXhigh = Beta::BetaManagedAgentsEffortXhigh

    module Beta
      type beta_managed_agents_effort_xhigh =
        { type: Anthropic::Models::Beta::BetaManagedAgentsEffortXhigh::type_ }

      class BetaManagedAgentsEffortXhigh < Anthropic::Internal::Type::BaseModel
        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsEffortXhigh::type_

        def initialize: (
          type: Anthropic::Models::Beta::BetaManagedAgentsEffortXhigh::type_
        ) -> void

        def to_hash: -> {
          type: Anthropic::Models::Beta::BetaManagedAgentsEffortXhigh::type_
        }

        type type_ = :xhigh

        module Type
          extend Anthropic::Internal::Type::Enum

          XHIGH: :xhigh

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsEffortXhigh::type_]
        end
      end
    end
  end
end
