module Anthropic
  module Models
    class BetaManagedAgentsVaultNotFoundDeploymentPausedReasonError = Beta::BetaManagedAgentsVaultNotFoundDeploymentPausedReasonError

    module Beta
      type beta_managed_agents_vault_not_found_deployment_paused_reason_error =
        {
          type: Anthropic::Models::Beta::BetaManagedAgentsVaultNotFoundDeploymentPausedReasonError::type_
        }

      class BetaManagedAgentsVaultNotFoundDeploymentPausedReasonError < Anthropic::Internal::Type::BaseModel
        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsVaultNotFoundDeploymentPausedReasonError::type_

        def initialize: (
          type: Anthropic::Models::Beta::BetaManagedAgentsVaultNotFoundDeploymentPausedReasonError::type_
        ) -> void

        def to_hash: -> {
          type: Anthropic::Models::Beta::BetaManagedAgentsVaultNotFoundDeploymentPausedReasonError::type_
        }

        type type_ = :vault_not_found_error

        module Type
          extend Anthropic::Internal::Type::Enum

          VAULT_NOT_FOUND_ERROR: :vault_not_found_error

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsVaultNotFoundDeploymentPausedReasonError::type_]
        end
      end
    end
  end
end
