module Anthropic
  module Models
    class BetaWebhookSessionThreadTerminatedEventData = Beta::BetaWebhookSessionThreadTerminatedEventData

    module Beta
      type beta_webhook_session_thread_terminated_event_data =
        {
          id: String,
          organization_id: String,
          session_thread_id: String,
          type: :"session.thread_terminated",
          workspace_id: String
        }

      class BetaWebhookSessionThreadTerminatedEventData < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor organization_id: String

        attr_accessor session_thread_id: String

        attr_accessor type: :"session.thread_terminated"

        attr_accessor workspace_id: String

        def initialize: (
          id: String,
          organization_id: String,
          session_thread_id: String,
          workspace_id: String,
          ?type: :"session.thread_terminated"
        ) -> void

        def to_hash: -> {
          id: String,
          organization_id: String,
          session_thread_id: String,
          type: :"session.thread_terminated",
          workspace_id: String
        }
      end
    end
  end
end
