module Anthropic
  module Models
    class BetaManagedAgentsEnvironmentArchivedDeploymentPausedReasonError = Beta::BetaManagedAgentsEnvironmentArchivedDeploymentPausedReasonError

    module Beta
      type beta_managed_agents_environment_archived_deployment_paused_reason_error =
        {
          type: Anthropic::Models::Beta::BetaManagedAgentsEnvironmentArchivedDeploymentPausedReasonError::type_
        }

      class BetaManagedAgentsEnvironmentArchivedDeploymentPausedReasonError < Anthropic::Internal::Type::BaseModel
        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsEnvironmentArchivedDeploymentPausedReasonError::type_

        def initialize: (
          type: Anthropic::Models::Beta::BetaManagedAgentsEnvironmentArchivedDeploymentPausedReasonError::type_
        ) -> void

        def to_hash: -> {
          type: Anthropic::Models::Beta::BetaManagedAgentsEnvironmentArchivedDeploymentPausedReasonError::type_
        }

        type type_ = :environment_archived_error

        module Type
          extend Anthropic::Internal::Type::Enum

          ENVIRONMENT_ARCHIVED_ERROR: :environment_archived_error

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsEnvironmentArchivedDeploymentPausedReasonError::type_]
        end
      end
    end
  end
end
