module Anthropic
  module Models
    class BetaManagedAgentsSessionCreationRejectedRunError = Beta::BetaManagedAgentsSessionCreationRejectedRunError

    module Beta
      type beta_managed_agents_session_creation_rejected_run_error =
        {
          message: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionCreationRejectedRunError::type_
        }

      class BetaManagedAgentsSessionCreationRejectedRunError < Anthropic::Internal::Type::BaseModel
        attr_accessor message: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsSessionCreationRejectedRunError::type_

        def initialize: (
          message: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionCreationRejectedRunError::type_
        ) -> void

        def to_hash: -> {
          message: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionCreationRejectedRunError::type_
        }

        type type_ = :session_creation_rejected_error

        module Type
          extend Anthropic::Internal::Type::Enum

          SESSION_CREATION_REJECTED_ERROR: :session_creation_rejected_error

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionCreationRejectedRunError::type_]
        end
      end
    end
  end
end
