module Anthropic
  module Models
    class BetaManagedAgentsSchedule = Beta::BetaManagedAgentsSchedule

    module Beta
      type beta_managed_agents_schedule =
        {
          expression: String,
          timezone: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSchedule::type_,
          last_run_at: Time?,
          upcoming_runs_at: ::Array[Time]
        }

      class BetaManagedAgentsSchedule < Anthropic::Internal::Type::BaseModel
        attr_accessor expression: String

        attr_accessor timezone: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsSchedule::type_

        attr_accessor last_run_at: Time?

        attr_reader upcoming_runs_at: ::Array[Time]?

        def upcoming_runs_at=: (::Array[Time]) -> ::Array[Time]

        def initialize: (
          expression: String,
          timezone: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSchedule::type_,
          ?last_run_at: Time?,
          ?upcoming_runs_at: ::Array[Time]
        ) -> void

        def to_hash: -> {
          expression: String,
          timezone: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSchedule::type_,
          last_run_at: Time?,
          upcoming_runs_at: ::Array[Time]
        }

        type type_ = :cron

        module Type
          extend Anthropic::Internal::Type::Enum

          CRON: :cron

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsSchedule::type_]
        end
      end
    end
  end
end
