module Anthropic
  module Models
    class BetaWebhookEnvironmentArchivedEventData = Beta::BetaWebhookEnvironmentArchivedEventData

    module Beta
      type beta_webhook_environment_archived_event_data =
        {
          id: String,
          organization_id: String,
          type: :"environment.archived",
          workspace_id: String
        }

      class BetaWebhookEnvironmentArchivedEventData < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor organization_id: String

        attr_accessor type: :"environment.archived"

        attr_accessor workspace_id: String

        def initialize: (
          id: String,
          organization_id: String,
          workspace_id: String,
          ?type: :"environment.archived"
        ) -> void

        def to_hash: -> {
          id: String,
          organization_id: String,
          type: :"environment.archived",
          workspace_id: String
        }
      end
    end
  end
end
