module Anthropic
  module Models
    module BetaManagedAgentsDeploymentStatus = Beta::BetaManagedAgentsDeploymentStatus

    module Beta
      type beta_managed_agents_deployment_status = :active | :paused

      module BetaManagedAgentsDeploymentStatus
        extend Anthropic::Internal::Type::Enum

        ACTIVE: :active
        PAUSED: :paused

        def self?.values: -> ::Array[Anthropic::Models::Beta::beta_managed_agents_deployment_status]
      end
    end
  end
end
