module Anthropic
  module Models
    class BetaManagedAgentsModelConfig = Beta::BetaManagedAgentsModelConfig

    module Beta
      type beta_managed_agents_model_config =
        {
          id: Anthropic::Models::Beta::beta_managed_agents_model,
          effort: Anthropic::Models::Beta::BetaManagedAgentsModelConfig::effort,
          speed: Anthropic::Models::Beta::BetaManagedAgentsModelConfig::speed
        }

      class BetaManagedAgentsModelConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor id: Anthropic::Models::Beta::beta_managed_agents_model

        attr_reader effort: Anthropic::Models::Beta::BetaManagedAgentsModelConfig::effort?

        def effort=: (
          Anthropic::Models::Beta::BetaManagedAgentsModelConfig::effort
        ) -> Anthropic::Models::Beta::BetaManagedAgentsModelConfig::effort

        attr_reader speed: Anthropic::Models::Beta::BetaManagedAgentsModelConfig::speed?

        def speed=: (
          Anthropic::Models::Beta::BetaManagedAgentsModelConfig::speed
        ) -> Anthropic::Models::Beta::BetaManagedAgentsModelConfig::speed

        def initialize: (
          id: Anthropic::Models::Beta::beta_managed_agents_model,
          ?effort: Anthropic::Models::Beta::BetaManagedAgentsModelConfig::effort,
          ?speed: Anthropic::Models::Beta::BetaManagedAgentsModelConfig::speed
        ) -> void

        def to_hash: -> {
          id: Anthropic::Models::Beta::beta_managed_agents_model,
          effort: Anthropic::Models::Beta::BetaManagedAgentsModelConfig::effort,
          speed: Anthropic::Models::Beta::BetaManagedAgentsModelConfig::speed
        }

        type effort =
          Anthropic::Beta::BetaManagedAgentsEffortLow
          | Anthropic::Beta::BetaManagedAgentsEffortMedium
          | Anthropic::Beta::BetaManagedAgentsEffortHigh
          | Anthropic::Beta::BetaManagedAgentsEffortXhigh
          | Anthropic::Beta::BetaManagedAgentsEffortMax

        module Effort
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsModelConfig::effort]
        end

        type speed = :standard | :fast

        module Speed
          extend Anthropic::Internal::Type::Enum

          STANDARD: :standard
          FAST: :fast

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsModelConfig::speed]
        end
      end
    end
  end
end
