module Anthropic
  module Models
    class BetaManagedAgentsSystemContentBlock = Beta::BetaManagedAgentsSystemContentBlock

    module Beta
      type beta_managed_agents_system_content_block =
        {
          text: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSystemContentBlock::type_
        }

      class BetaManagedAgentsSystemContentBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor text: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsSystemContentBlock::type_

        def initialize: (
          text: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSystemContentBlock::type_
        ) -> void

        def to_hash: -> {
          text: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsSystemContentBlock::type_
        }

        type type_ = :text

        module Type
          extend Anthropic::Internal::Type::Enum

          TEXT: :text

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsSystemContentBlock::type_]
        end
      end
    end
  end
end
