module Anthropic
  module Models
    class BetaManagedAgentsDeploymentUserDefineOutcomeEvent = Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent

    module Beta
      type beta_managed_agents_deployment_user_define_outcome_event =
        {
          description: String,
          rubric: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::rubric,
          type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::type_,
          max_iterations: Integer?
        }

      class BetaManagedAgentsDeploymentUserDefineOutcomeEvent < Anthropic::Internal::Type::BaseModel
        attr_accessor description: String

        attr_accessor rubric: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::rubric

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::type_

        attr_accessor max_iterations: Integer?

        def initialize: (
          description: String,
          rubric: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::rubric,
          type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::type_,
          ?max_iterations: Integer?
        ) -> void

        def to_hash: -> {
          description: String,
          rubric: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::rubric,
          type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::type_,
          max_iterations: Integer?
        }

        type rubric =
          Anthropic::Beta::Sessions::BetaManagedAgentsFileRubric
          | Anthropic::Beta::Sessions::BetaManagedAgentsTextRubric

        module Rubric
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::rubric]
        end

        type type_ = :"user.define_outcome"

        module Type
          extend Anthropic::Internal::Type::Enum

          USER_DEFINE_OUTCOME: :"user.define_outcome"

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentUserDefineOutcomeEvent::type_]
        end
      end
    end
  end
end
