module Anthropic
  module Models
    class BetaMessageDeltaUsage = Beta::BetaMessageDeltaUsage

    module Beta
      type beta_message_delta_usage =
        {
          cache_creation_input_tokens: Integer?,
          cache_read_input_tokens: Integer?,
          input_tokens: Integer?,
          iterations: Anthropic::Models::Beta::beta_iterations_usage?,
          output_tokens: Integer,
          output_tokens_details: Anthropic::Beta::BetaOutputTokensDetails?,
          server_tool_use: Anthropic::Beta::BetaServerToolUsage?
        }

      class BetaMessageDeltaUsage < Anthropic::Internal::Type::BaseModel
        attr_accessor cache_creation_input_tokens: Integer?

        attr_accessor cache_read_input_tokens: Integer?

        attr_accessor input_tokens: Integer?

        attr_accessor iterations: Anthropic::Models::Beta::beta_iterations_usage?

        attr_accessor output_tokens: Integer

        attr_accessor output_tokens_details: Anthropic::Beta::BetaOutputTokensDetails?

        attr_accessor server_tool_use: Anthropic::Beta::BetaServerToolUsage?

        def initialize: (
          cache_creation_input_tokens: Integer?,
          cache_read_input_tokens: Integer?,
          input_tokens: Integer?,
          iterations: Anthropic::Models::Beta::beta_iterations_usage?,
          output_tokens: Integer,
          output_tokens_details: Anthropic::Beta::BetaOutputTokensDetails?,
          server_tool_use: Anthropic::Beta::BetaServerToolUsage?
        ) -> void

        def to_hash: -> {
          cache_creation_input_tokens: Integer?,
          cache_read_input_tokens: Integer?,
          input_tokens: Integer?,
          iterations: Anthropic::Models::Beta::beta_iterations_usage?,
          output_tokens: Integer,
          output_tokens_details: Anthropic::Beta::BetaOutputTokensDetails?,
          server_tool_use: Anthropic::Beta::BetaServerToolUsage?
        }
      end
    end
  end
end
