module Anthropic
  module Models
    class BetaManagedAgentsMemoryStoreArchivedRunError = Beta::BetaManagedAgentsMemoryStoreArchivedRunError

    module Beta
      type beta_managed_agents_memory_store_archived_run_error =
        {
          message: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreArchivedRunError::type_
        }

      class BetaManagedAgentsMemoryStoreArchivedRunError < Anthropic::Internal::Type::BaseModel
        attr_accessor message: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreArchivedRunError::type_

        def initialize: (
          message: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreArchivedRunError::type_
        ) -> void

        def to_hash: -> {
          message: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreArchivedRunError::type_
        }

        type type_ = :memory_store_archived_error

        module Type
          extend Anthropic::Internal::Type::Enum

          MEMORY_STORE_ARCHIVED_ERROR: :memory_store_archived_error

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreArchivedRunError::type_]
        end
      end
    end
  end
end
