module Anthropic
  module Models
    class BetaManagedAgentsGitHubRepositoryResourceConfig = Beta::BetaManagedAgentsGitHubRepositoryResourceConfig

    module Beta
      type beta_managed_agents_github_repository_resource_config =
        {
          type: Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::type_,
          url: String,
          checkout: Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::checkout?,
          mount_path: String?
        }

      class BetaManagedAgentsGitHubRepositoryResourceConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::type_

        attr_accessor url: String

        attr_accessor checkout: Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::checkout?

        attr_accessor mount_path: String?

        def initialize: (
          type: Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::type_,
          url: String,
          ?checkout: Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::checkout?,
          ?mount_path: String?
        ) -> void

        def to_hash: -> {
          type: Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::type_,
          url: String,
          checkout: Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::checkout?,
          mount_path: String?
        }

        type type_ = :github_repository

        module Type
          extend Anthropic::Internal::Type::Enum

          GITHUB_REPOSITORY: :github_repository

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::type_]
        end

        type checkout =
          Anthropic::Beta::BetaManagedAgentsBranchCheckout
          | Anthropic::Beta::BetaManagedAgentsCommitCheckout

        module Checkout
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsGitHubRepositoryResourceConfig::checkout]
        end
      end
    end
  end
end
