module Anthropic
  module Models
    class BetaManagedAgentsMemoryStoreResourceConfig = Beta::BetaManagedAgentsMemoryStoreResourceConfig

    module Beta
      type beta_managed_agents_memory_store_resource_config =
        {
          memory_store_id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::type_,
          access: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::access?,
          instructions: String?
        }

      class BetaManagedAgentsMemoryStoreResourceConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor memory_store_id: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::type_

        attr_accessor access: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::access?

        attr_accessor instructions: String?

        def initialize: (
          memory_store_id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::type_,
          ?access: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::access?,
          ?instructions: String?
        ) -> void

        def to_hash: -> {
          memory_store_id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::type_,
          access: Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::access?,
          instructions: String?
        }

        type type_ = :memory_store

        module Type
          extend Anthropic::Internal::Type::Enum

          MEMORY_STORE: :memory_store

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::type_]
        end

        type access = :read_write | :read_only

        module Access
          extend Anthropic::Internal::Type::Enum

          READ_WRITE: :read_write
          READ_ONLY: :read_only

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMemoryStoreResourceConfig::access]
        end
      end
    end
  end
end
