module Anthropic
  module Models
    module Beta
      type deployment_run_list_params =
        {
          created_at_gt: Time,
          created_at_gte: Time,
          created_at_lt: Time,
          created_at_lte: Time,
          deployment_id: String,
          has_error: bool,
          limit: Integer,
          page: String,
          trigger_type: Anthropic::Models::Beta::beta_managed_agents_trigger_type,
          betas: ::Array[Anthropic::Models::anthropic_beta]
        }
        & Anthropic::Internal::Type::request_parameters

      class DeploymentRunListParams < Anthropic::Internal::Type::BaseModel
        extend Anthropic::Internal::Type::RequestParameters::Converter
        include Anthropic::Internal::Type::RequestParameters

        attr_reader created_at_gt: Time?

        def created_at_gt=: (Time) -> Time

        attr_reader created_at_gte: Time?

        def created_at_gte=: (Time) -> Time

        attr_reader created_at_lt: Time?

        def created_at_lt=: (Time) -> Time

        attr_reader created_at_lte: Time?

        def created_at_lte=: (Time) -> Time

        attr_reader deployment_id: String?

        def deployment_id=: (String) -> String

        attr_reader has_error: bool?

        def has_error=: (bool) -> bool

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader page: String?

        def page=: (String) -> String

        attr_reader trigger_type: Anthropic::Models::Beta::beta_managed_agents_trigger_type?

        def trigger_type=: (
          Anthropic::Models::Beta::beta_managed_agents_trigger_type
        ) -> Anthropic::Models::Beta::beta_managed_agents_trigger_type

        attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

        def betas=: (
          ::Array[Anthropic::Models::anthropic_beta]
        ) -> ::Array[Anthropic::Models::anthropic_beta]

        def initialize: (
          ?created_at_gt: Time,
          ?created_at_gte: Time,
          ?created_at_lt: Time,
          ?created_at_lte: Time,
          ?deployment_id: String,
          ?has_error: bool,
          ?limit: Integer,
          ?page: String,
          ?trigger_type: Anthropic::Models::Beta::beta_managed_agents_trigger_type,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> void

        def to_hash: -> {
          created_at_gt: Time,
          created_at_gte: Time,
          created_at_lt: Time,
          created_at_lte: Time,
          deployment_id: String,
          has_error: bool,
          limit: Integer,
          page: String,
          trigger_type: Anthropic::Models::Beta::beta_managed_agents_trigger_type,
          betas: ::Array[Anthropic::Models::anthropic_beta],
          request_options: Anthropic::RequestOptions
        }
      end
    end
  end
end
