module Anthropic
  module Resources
    class Beta
      attr_reader models: Anthropic::Resources::Beta::Models

      attr_reader messages: Anthropic::Resources::Beta::Messages

      attr_reader agents: Anthropic::Resources::Beta::Agents

      attr_reader environments: Anthropic::Resources::Beta::Environments

      attr_reader sessions: Anthropic::Resources::Beta::Sessions

      attr_reader deployments: Anthropic::Resources::Beta::Deployments

      attr_reader deployment_runs: Anthropic::Resources::Beta::DeploymentRuns

      attr_reader vaults: Anthropic::Resources::Beta::Vaults

      attr_reader memory_stores: Anthropic::Resources::Beta::MemoryStores

      attr_reader files: Anthropic::Resources::Beta::Files

      attr_reader skills: Anthropic::Resources::Beta::Skills

      attr_reader webhooks: Anthropic::Resources::Beta::Webhooks

      attr_reader user_profiles: Anthropic::Resources::Beta::UserProfiles

      def initialize: (client: Anthropic::Client) -> void
    end
  end
end
