module Anthropic
  module Resources
    class Beta
      class Deployments
        def create: (
          agent: Anthropic::Models::Beta::DeploymentCreateParams::agent,
          environment_id: String,
          initial_events: ::Array[Anthropic::Models::Beta::beta_managed_agents_deployment_initial_event_params],
          name: String,
          ?description: String?,
          ?metadata: ::Hash[Symbol, String],
          ?resources: ::Array[Anthropic::Models::Beta::DeploymentCreateParams::resource],
          ?schedule: Anthropic::Beta::BetaManagedAgentsScheduleParams?,
          ?vault_ids: ::Array[String],
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsDeployment

        def retrieve: (
          String deployment_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsDeployment

        def update: (
          String deployment_id,
          ?agent: Anthropic::Models::Beta::DeploymentUpdateParams::agent,
          ?description: String?,
          ?environment_id: String,
          ?initial_events: ::Array[Anthropic::Models::Beta::beta_managed_agents_deployment_initial_event_params],
          ?metadata: ::Hash[Symbol, String?]?,
          ?name: String,
          ?resources: ::Array[Anthropic::Models::Beta::DeploymentUpdateParams::resource]?,
          ?schedule: Anthropic::Beta::BetaManagedAgentsScheduleParams?,
          ?vault_ids: ::Array[String]?,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsDeployment

        def list: (
          ?agent_id: String,
          ?created_at_gte: Time,
          ?created_at_lte: Time,
          ?include_archived: bool,
          ?limit: Integer,
          ?page: String,
          ?status: Anthropic::Models::Beta::beta_managed_agents_deployment_status,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Internal::PageCursor[Anthropic::Beta::BetaManagedAgentsDeployment]

        def archive: (
          String deployment_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsDeployment

        def pause: (
          String deployment_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsDeployment

        def run: (
          String deployment_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsDeploymentRun

        def unpause: (
          String deployment_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsDeployment

        def initialize: (client: Anthropic::Client) -> void
      end
    end
  end
end
