module Anthropic
  module Resources
    class Beta
      class Sessions
        attr_reader events: Anthropic::Resources::Beta::Sessions::Events

        attr_reader resources: Anthropic::Resources::Beta::Sessions::Resources

        attr_reader threads: Anthropic::Resources::Beta::Sessions::Threads

        def create: (
          agent: Anthropic::Models::Beta::SessionCreateParams::agent,
          environment_id: String,
          ?initial_events: ::Array[Anthropic::Models::Beta::SessionCreateParams::initial_event],
          ?metadata: ::Hash[Symbol, String],
          ?resources: ::Array[Anthropic::Models::Beta::SessionCreateParams::resource],
          ?title: String?,
          ?vault_ids: ::Array[String],
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsSession

        def retrieve: (
          String session_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsSession

        def update: (
          String session_id,
          ?agent: Anthropic::Beta::BetaManagedAgentsSessionAgentUpdate,
          ?metadata: ::Hash[Symbol, String?]?,
          ?title: String?,
          ?vault_ids: ::Array[String],
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsSession

        def list: (
          ?agent_id: String,
          ?agent_version: Integer,
          ?created_at_gt: Time,
          ?created_at_gte: Time,
          ?created_at_lt: Time,
          ?created_at_lte: Time,
          ?deployment_id: String,
          ?include_archived: bool,
          ?limit: Integer,
          ?memory_store_id: String,
          ?order: Anthropic::Models::Beta::SessionListParams::order,
          ?page: String,
          ?statuses: ::Array[Anthropic::Models::Beta::SessionListParams::status],
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Internal::BidirectionalPageCursor[Anthropic::Beta::BetaManagedAgentsSession]

        def delete: (
          String session_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsDeletedSession

        def archive: (
          String session_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaManagedAgentsSession

        def initialize: (client: Anthropic::Client) -> void
      end
    end
  end
end
